In [4]:
# import important libraries
import numpy as np
import pandas as pd
import joblib
from sklearn.preprocessing import StandardScaler

# Calculate the person have heart disease or not

In [6]:
heart = joblib.load("heart.joblib")

In [10]:
age = int(input("Enter age:"))
sex = int(input("Enter sex:")) 
cp = int(input("Enter cp:")) 
trestbps = int(input("Enter trestbps:")) 
chol = int(input("Enter chol:")) 
fbs = int(input("Enter fbs:")) 
restecg = int(input("Enter restecg:")) 
thalach = int(input("Enter thalach:")) 
exang = int(input("Enter exang:")) 
oldpeak = float(input("Enter oldpeak:")) 
slope = int(input("Enter slope:")) 
ca = int(input("Enter ca:")) 
thal = int(input("Enter thal:"))

Enter age: 25
Enter sex: 1
Enter cp: 2
Enter trestbps: 4
Enter chol: 85
Enter fbs: 2
Enter restecg: 4
Enter thalach: 25
Enter exang: 2
Enter oldpeak: 4
Enter slope: 53
Enter ca: 2
Enter thal: 1


In [24]:
data = (age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal)
print(data)
data_np = np.asarray(data)
x = data_np.reshape(1,-1)
sc = StandardScaler()
sc_x = sc.fit_transform(x)
heart.predict(sc_x)

(25, 1, 2, 4, 85, 2, 4, 25, 2, 4.0, 53, 2, 1)


C:\Users\Omkar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

# Calculate the person have diabetes or not

In [12]:
biabetes = joblib.load("diabetes.joblib")

In [19]:
Pregnancies = int(input("Enter Pregnancies :"))
Glucose = int(input("Enter Glucose :"))
BloodPressure = int(input("Enter BloodPressure :"))
SkinThickness = int(input("Enter SkinThickness :"))
Insulin = int(input("Enter Insulin :"))
BMI = float(input("Enter BMI :"))
DiabetesPedigreeFunction = float(input("Enter DiabetesPedigreeFunction :"))
Age  = int(input("Enter Age :"))  

#Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age

Enter Pregnancies : 25
Enter Glucose : 85
Enter BloodPressure : 52
Enter SkinThickness : 55
Enter Insulin : 52
Enter BMI : 8.3
Enter DiabetesPedigreeFunction : 52
Enter Age : 25


In [25]:
data = (Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age)
print(data)
data_np = np.asarray(data)
x = data_np.reshape(1,-1)
sc = StandardScaler()
sc_x = sc.fit_transform(x)
biabetes.predict(sc_x)

(25, 85, 52, 55, 52, 8.3, 52.0, 25)


C:\Users\Omkar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

# Calculate the person have breast canser or not or not

In [21]:
breast = joblib.load("breast.joblib")

In [22]:
mean_radius = float(input("Enter mean_radius :"))
mean_texture = float(input("Enter mean texture :"))
mean_perimeter = float(input("Enter mean perimeter :"))
mean_area = float(input("Enter mean area :"))
mean_smoothness = float(input("Enter mean smoothness :"))
mean_compactness = float(input("Enter mean compactness :"))
mean_concavity = float(input("Enter mean concavity :"))
mean_concave_points = float(input("Enter mean concave points :"))
mean_symmetry = float(input("Enter mean symmetry :"))
mean_fractal_dimension = float(input("Enter mean fractal dimension :"))
radius_error = float(input("Enter radius error :"))
texture_error = float(input("Enter texture error :"))
perimeter_error = float(input("Enter perimeter error :"))
area_error = float(input("Enter area error :"))
smoothness_error = float(input("Enter smoothness error :"))
compactness_error = float(input("Enter compactness error :"))
concavity_error = float(input("Enter concavity error :"))
concave_points_error = float(input("Enter concave points error :"))
symmetry_error = float(input("Enter symmetry error :"))
fractal_dimension_error = float(input("Enter fractal dimension error :"))
worst_radius = float(input("Enter worst radius :"))
worst_texture = float(input("Enter worst texture :"))
worst_perimeter = float(input("Enter worst perimeter :"))
worst_area = float(input("Enter worst area :"))
worst_smoothness = float(input("Enterworst smoothness :"))
worst_compactness = float(input("Enter worst compactness :"))
worst_concavity = float(input("Enter worst concavity :"))
worst_concave_points = float(input("Enter worst concave points :"))
worst_symmetry = float(input("Enter worst symmetry :"))
worst_fractal_dimension = float(input("Enter worst fractal dimension :"))


# mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,
# mean_fractal_dimension,radius_error,texture_error,perimeter_error, area_error,smoothness_error, compactness_error,concavity_error,
# concave_points_error,symmetry_error,fractal_dimension_error, worst_radius,worst_texture,worst_perimeter, worst_area,worst_smoothness,
# worst_compactness,worst_concavity,worst_concave_points, worst_symmetry,worst_fractal_dimension

Enter mean_radius : 2.2
Enter mean texture : 2.5
Enter mean perimeter : 4.5
Enter mean area : 2.6
Enter mean smoothness : 3.4
Enter mean compactness : 5.2
Enter mean concavity : 7.5
Enter mean concave points : 8.
Enter mean symmetry : 5.6
Enter mean fractal dimension : 6.4
Enter radius error : 4.1
Enter texture error : 9.5
Enter perimeter error : 5.4
Enter area error : 7.9
Enter smoothness error : 8.3
Enter compactness error : 1.9
Enter concavity error : 5.6
Enter concave points error : 7.9
Enter symmetry error : 4.6
Enter fractal dimension error : 4.1
Enter worst radius : 8.6
Enter worst texture : 5.6
Enter worst perimeter : 4.6
Enter worst area : 8.9
Enterworst smoothness : 4.5
Enter worst compactness : 4.8
Enter worst concavity : 7.1
Enter worst concave points : 4.6
Enter worst symmetry : 1.2
Enter worst fractal dimension : 4.8


In [26]:
data = (
    mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,
    mean_fractal_dimension,radius_error,texture_error,perimeter_error, area_error,smoothness_error, compactness_error,concavity_error,
    concave_points_error,symmetry_error,fractal_dimension_error, worst_radius,worst_texture,worst_perimeter, worst_area,worst_smoothness,
    worst_compactness,worst_concavity,worst_concave_points, worst_symmetry,worst_fractal_dimension
)
print(data)
data_np = np.asarray(data)
x = data_np.reshape(1,-1)
sc = StandardScaler()
sc_x = sc.fit_transform(x)
breast.predict(sc_x)

(2.2, 2.5, 4.5, 2.6, 3.4, 5.2, 7.5, 8.0, 5.6, 6.4, 4.1, 9.5, 5.4, 7.9, 8.3, 1.9, 5.6, 7.9, 4.6, 4.1, 8.6, 5.6, 4.6, 8.9, 4.5, 4.8, 7.1, 4.6, 1.2, 4.8)


C:\Users\Omkar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1])